name: CI

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:



jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Successful compilation
        run: |
          sudo apt-get install -y libsdl2-dev
          ./compile.sh test
          ./compile.sh release

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Successful compilation
        run: |
          brew install sdl2
          ./compile.sh test
          ./compile.sh release
