name: CI

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:



jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Successful compilation
        run: |
          sudo apt-get -qq install -y libsdl2-dev # impatience lol
          ./compile test
          ./compile release
          ./run

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Successful compilation
        run: |
          brew install sdl2 # impatience lol
          ./compile test
          ./compile release
          ./run
