name: CI

on:
  push:
    branches: [ '*', '!main' ]
  workflow_dispatch:



jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make test
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-13 clang-13 llvm-13-dev libclang-13-dev
          make test
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Successful compilation
        run: |
          PATH=/usr/local/opt/llvm/bin:$PATH
          make test
